service: sls-s3-event-lambda
frameworkVersion: '3'
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  architecture: x86_64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "*"
custom:
  defaultStage: dev
package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  hello:
    handler: bin/main
    timeout: 30
    events: 
      - s3:
          bucket: ${self:custom.defaultStage}-sls-s3-event-lambda
          event: s3:ObjectCreated:*
          rules:
            - prefix: hello/
            - suffix: .txt
    reservedConcurrency: 3