service: sls-go-lambda
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  defaultStage: dev
custom:
  defaultStage: dev
package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  hello:
    handler: bin/main