service: sls-go-lambda
frameworkVersion: '3'
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  architecture: x86_64
custom:
  defaultStage: dev
package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  hello:
    handler: bin/main